In [45]:
import numpy as np
import pandas as pd
import torch

In [ ]:
def train_test_split(X, y, test_size:float = None, train_size:float = None):
	if X.shape[0] != y.shape[0]:
		raise Exception("Size mismatch of X and y")
	else:
		total_rows=X.shape[0]
	if test_size == None and train_size == None:
		test_size=0.25
		train_size = 1 - test_size
	elif test_size == None:
		test_size = 1 - train_size
	elif train_size == None:
		train_size = 1 - test_size

	mark = int(total_rows*train_size)
	return X[:mark], y[:mark], X[mark:], y[mark:]


In [ ]:
# from sklearn.model_selection import train_test_split
df = pd.read_csv('data.csv')
df.head()
X = df.drop(columns=['price']).to_numpy()
y = df['price'].to_numpy()

tensor([[ 750,    1],
        [ 900,    2],
        [1200,    2],
        [1500,    3],
        [1800,    3],
        [2000,    4],
        [2200,    4],
        [2500,    4],
        [2800,    5],
        [3000,    5]])

In [139]:
X_train, y_train, X_test, y_test = train_test_split(X, y, 0.2)
# Scaling
# from sklearn.preprocessing import StandardScaler
# scaler = StandardScaler()
# X_train = scaler.fit_transform(X_train)
# X_test = scaler.transform(X_test)
X_train

array([[ 750,    1],
       [ 900,    2],
       [1200,    2],
       [1500,    3],
       [1800,    3],
       [2000,    4],
       [2200,    4],
       [2500,    4]])

In [ ]:
class Perceptron():
	def __init__(self, features_size):
		self.weights = torch.tensor(np.random.random(features_size), requires_grad=True, dtype=torch.float32)
		self.bias = torch.tensor(np.random.random(), requires_grad=True, dtype=torch.float32)

	def forward(self, features):
		features = torch.tensor(features, dtype=torch.float32)
		self.model_pred = torch.empty(features.shape[0], dtype=torch.float32)
		for feature in features:
			# print(feature)
			self.model_pred.add(torch.dot(self.weights, feature) + self.bias)
			print(self.model_pred)
		# y_pred = []
		# for pred in self.model_pred:
		# 	y_pred.append(pred.detach())
		# return np.array(y_pred)
		return self.model_pred
			
	def rmse(self, y_true, y_pred):
		if y_true.shape != y_pred.shape:
			raise Exception("Shape mismatch(y_true and y_pred are not same shape)")
		y_true = torch.from_numpy(y_true)
		y_pred = torch.from_numpy(y_pred)
		num = y_true.shape[0]
		self.loss=[]
		for i in range(num):
			loss = torch.tensor((((y_true[i] - y_pred[i])**2)**0.5)/num, requires_grad=True)
			self.loss.append(loss)

		# loss = ((sum((y_true - y_pred)**2))**0.5)/num
		# self.loss = torch.tensor(((sum(y_true - y_pred)**2)**0.5)/num, requires_grad=True)
		return self.loss
	
	def backpropagation(self, lr=0.01):
		losses = self.loss
		for loss in losses:
			loss.backward()
			for i in range(len(self.weights)):
				self.weights[i] = self.weights[i] - (lr * self.weights[i].grad())
			self.bias = self.bias * (lr * self.bias.grad())


In [196]:
model = Perceptron(X_train.shape[1])

y_pred = (model.forward(X_train))

# Calculate loss

# loss = model.rmse(y_train, y_pred)

# model.weights.retain_grad()

# update weights 
# model.backpropagation(lr=0.01)
# model.weights[0].grad_fn

# print(y_pred, y_train)

y_pred

tensor([], grad_fn=<AddBackward0>)
tensor([], grad_fn=<AddBackward0>)
tensor([], grad_fn=<AddBackward0>)
tensor([], grad_fn=<AddBackward0>)
tensor([], grad_fn=<AddBackward0>)
tensor([], grad_fn=<AddBackward0>)
tensor([], grad_fn=<AddBackward0>)
tensor([], grad_fn=<AddBackward0>)


tensor([], grad_fn=<AddBackward0>)

In [ ]:
test = df.iloc[:2].to_numpy(dtype='float32')
for t in test:
  print(t)
# test = np.array(test)
# print(test)

2.069380665631977


In [56]:
y_t = np.array([1])
y_p = np.array([0.5])
((sum((y_t - y_p)**2))**0.5)/len(y_t)


np.float64(0.5)

In [212]:
t = torch.empty(X_train.shape[0])
for i in range(5):
	t[i] += i
t

tensor([4.4573e-11, 1.0000e+00, 2.0000e+00, 3.0000e+00, 4.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00])